version: '3.5'

services:
  activity:
    build:
      context: 'Docker/activity'
      args:
        uid: 1000
    volumes:
      - ./activity/public:/var/www/html
      - ./activity/:/var/www/
    ports:
      - "8080:80"
    depends_on:
      - mysql_activity
    links:
      - mysql_activity

  mysql_activity:
    image: mysql:8.0
    volumes:
      - ./activity/storage/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activity
