version: '3.5'

services:
  activity:
    build:
      context: './activity'
    volumes:
      - ./activity/public:/var/www/html
      - ./activity/:/var/www/
    ports:
      - "8081:80"
    depends_on:
      - mysql_activity
    links:
      - mysql_activity
  landing:
    build:
      context: './landing'
    volumes:
      - ./landing/public:/var/www/html
      - ./landing/:/var/www/
    ports:
      - "8080:80"
    depends_on:
      - activity
    links:
      - activity
  mysql_activity:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activity
